/*
 * Copyright (c) 2022 Contributors to the Eclipse Foundation.
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   SmartCity Jena, Stefan Bischof - initial
 *
 */
package org.eclipse.daanse.olap.rolap.dbmapper.model.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.eclipse.daanse.olap.rolap.dbmapper.model.api.MappingAutoGeneratedDateTable;
import org.eclipse.daanse.olap.rolap.dbmapper.model.api.MappingTableElement;
import org.eclipse.daanse.olap.rolap.dbmapper.model.jaxb.adapter.InstantXmlAdapter;

import java.time.Instant;
import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AutoGeneratedDateTable", propOrder = { "tableElement" })
public class AutoGeneratedDateTableImpl implements MappingAutoGeneratedDateTable {


    @XmlElements({ @XmlElement(name = "ColumnDefs", type = ColumnDefsImpl.class),
        @XmlElement(name = "Hint", type = HintImpl.class), @XmlElement(name = "Key", type = KeyImpl.class) })
    private List<MappingTableElement> tableElement;

    @XmlAttribute(name = "startDate")
    @XmlJavaTypeAdapter(InstantXmlAdapter.class)
    private Instant startDate;

    @XmlAttribute(name = "endDate")
    @XmlJavaTypeAdapter(InstantXmlAdapter.class)
    private Instant endDate;

    @XmlAttribute(name = "name")
    private String name;

    @XmlAttribute(name = "schema")
    private String schema;

    @XmlAttribute(name = "alias")
    private String alias;

    @XmlAttribute(name = "keyColumn")
    private String keyColumn;

    @Override
    public List<MappingTableElement> tableElement() {
        return tableElement;
    }

    public void setTableElement(List<MappingTableElement> tableElement) {
        this.tableElement = tableElement;
    }

    @Override
    public Instant startDate() {
        return startDate;
    }

    public void setStartDate(Instant startDate) {
        this.startDate = startDate;
    }

    @Override
    public Instant endDate() {
        return endDate;
    }

    public void setEndDate(Instant endDate) {
        this.endDate = endDate;
    }

    @Override
    public String name() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String schema() {
        return schema;
    }

    public void setSchema(String schema) {
        this.schema = schema;
    }

    @Override
    public String alias() {
        return alias;
    }

    public void setAlias(String alias) {
        this.alias = alias;
    }

    @Override
    public String keyColumn() {
        return keyColumn;
    }

    public void setKeyColumn(String keyColumn) {
        this.keyColumn = keyColumn;
    }
}
