package org.eclipse.daanse.olap.rolap.dbmapper.model.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlType;
import org.eclipse.daanse.olap.rolap.dbmapper.model.api.MappingPhysicalSchema;
import org.eclipse.daanse.olap.rolap.dbmapper.model.api.MappingPhysicalSchemaElement;

import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PhysicalSchema")
public class PhysicalSchemaImpl implements MappingPhysicalSchema {

    @XmlElements({ @XmlElement(name = "AutoGeneratedDateTable", type = AutoGeneratedDateTableImpl.class)})
    List<MappingPhysicalSchemaElement> childrens;

    @Override
    public List<MappingPhysicalSchemaElement> children() {
        return childrens;
    }
}
